export const searchDummy = {
  data: [
    {
      musicId: 47387,
      num: '99686',
      title: '소백산아리랑',
      singer: '조윤선',
      lyricist: '이용백',
      composer: '문정기',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=99686',
      nation: 'KOR',
    },
    {
      musicId: 7624,
      num: '9877',
      title: '아리랑(붉은악마국민응원가)',
      singer: '윤도현밴드',
      lyricist: '민요',
      composer: '민요',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=9877',
      nation: 'KOR',
    },
    {
      musicId: 46880,
      num: '98645',
      title: '상주아리랑',
      singer: '김정아',
      lyricist: '김정아',
      composer: '유하정',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=98645',
      nation: 'KOR',
    },
    {
      musicId: 46046,
      num: '97810',
      title: '홀로아리랑',
      singer: '부활',
      lyricist: '한돌',
      composer: '한돌',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=97810',
      nation: 'KOR',
    },
    {
      musicId: 44196,
      num: '95959',
      title: '서천아리랑',
      singer: '임채희',
      lyricist: '박용갑',
      composer: '황선우',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=95959',
      nation: 'KOR',
    },
    {
      musicId: 43684,
      num: '95447',
      title: '행복아리랑',
      singer: '김진이',
      lyricist: '김진이',
      composer: '최석원',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=95447',
      nation: 'KOR',
    },
    {
      musicId: 43561,
      num: '95324',
      title: '대구아리랑',
      singer: '홍나영',
      lyricist: '홍나영',
      composer: '이재인',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=95324',
      nation: 'KOR',
    },
    {
      musicId: 43415,
      num: '95178',
      title: '대장부아리랑',
      singer: '황인성',
      lyricist: '황인성',
      composer: '송결',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=95178',
      nation: 'KOR',
    },
    {
      musicId: 42399,
      num: '89905',
      title: '청춘아리랑',
      singer: '최연수',
      lyricist: '송광호',
      composer: '송광호',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=89905',
      nation: 'KOR',
    },
    {
      musicId: 6317,
      num: '8562',
      title: '울산아리랑',
      singer: '오은정',
      lyricist: '오은정',
      composer: '김정일',
      youtubeUrl: 'https://www.youtube.com/user/ziller/search?query=8562',
      nation: 'KOR',
    },
  ],
  pageInfo: {
    page: 0,
    size: 10,
    totalElements: 59,
    totalPages: 6,
  },
};

export const populerDummy = {
  data: [
    {
      ranking: '1',
      num: '83138',
      title: '심(心)',
      singer: 'DK(디셈버)',
    },
    {
      ranking: '2',
      num: '81425',
      title: '사건의지평선',
      singer: '윤하',
    },
    {
      ranking: '3',
      num: '14515',
      title: '응급실(쾌걸춘향OST)',
      singer: 'izi',
    },
    {
      ranking: '4',
      num: '46108',
      title: '다시사랑한다면(니글니글버터플라이)',
      singer: '김필',
    },
    {
      ranking: '5',
      num: '82308',
      title: 'Monologue',
      singer: 'tei',
    },
    {
      ranking: '6',
      num: '47835',
      title: '그대라는사치',
      singer: '한동근',
    },
    {
      ranking: '7',
      num: '46009',
      title: '어디에도',
      singer: 'MC THE MAX',
    },
    {
      ranking: '8',
      num: '46213',
      title: 'Marry Me',
      singer: '마크툽(MAKTUB),구윤회',
    },
    {
      ranking: '9',
      num: '81405',
      title: '내가아니라도',
      singer: '주호',
    },
    {
      ranking: '10',
      num: '38028',
      title: '너의모든순간(별에서온그대OST)',
      singer: '성시경',
    },
    {
      ranking: '11',
      num: '49818',
      title: '좋니',
      singer: '윤종신',
    },
    {
      ranking: '12',
      num: '82802',
      title: 'Ditto',
      singer: 'NewJeans',
    },
    {
      ranking: '13',
      num: '2730',
      title: '가질수없는너',
      singer: '뱅크',
    },
    {
      ranking: '14',
      num: '11491',
      title: '소주한잔',
      singer: '임창정',
    },
    {
      ranking: '15',
      num: '48470',
      title: '첫눈처럼너에게가겠다(도깨비OST)',
      singer: '에일리',
    },
    {
      ranking: '16',
      num: '48462',
      title: '나에게로의초대(이상한나라의앨리스,하트다하트여왕)',
      singer: '조유진,박기영',
    },
    {
      ranking: '17',
      num: '78872',
      title: '첫사랑',
      singer: '백아',
    },
    {
      ranking: '18',
      num: '80906',
      title: '취중고백',
      singer: '김민석',
    },
    {
      ranking: '19',
      num: '17489',
      title: '비밀번호 486',
      singer: '윤하',
    },
    {
      ranking: '20',
      num: '13588',
      title: '삭제',
      singer: '이승기',
    },
    {
      ranking: '21',
      num: '9986',
      title: '그래서그대는',
      singer: '얀',
    },
    {
      ranking: '22',
      num: '10842',
      title: '희재(국화꽃향기OST)',
      singer: '성시경',
    },
    {
      ranking: '23',
      num: '81776',
      title: '해요(2022)',
      singer: '#안녕',
    },
    {
      ranking: '24',
      num: '96763',
      title: '꿈속에너',
      singer: '에이치코드(Feat.전상근)',
    },
    {
      ranking: '25',
      num: '82072',
      title: 'Hype boy',
      singer: 'NewJeans',
    },
    {
      ranking: '26',
      num: '91507',
      title: '포장마차',
      singer: '황인욱',
    },
    {
      ranking: '27',
      num: '46262',
      title: '봄이좋냐??',
      singer: '10cm',
    },
    {
      ranking: '28',
      num: '34409',
      title: 'Hello',
      singer: '허각',
    },
    {
      ranking: '29',
      num: '82666',
      title: '와스레나이',
      singer: '다나카(TANAKA)(Prod By 디핵(D-Hack))',
    },
    {
      ranking: '30',
      num: '82692',
      title: '잘가요',
      singer: '주호',
    },
    {
      ranking: '31',
      num: '80548',
      title: '사랑은늘도망가(신사와아가씨OST)',
      singer: '임영웅',
    },
    {
      ranking: '32',
      num: '35819',
      title: '오래된노래',
      singer: '스탠딩에그',
    },
    {
      ranking: '33',
      num: '80469',
      title: '찰나가영원이될때(The Eternal Moment)',
      singer: '마크툽(MAKTUB)',
    },
    {
      ranking: '34',
      num: '8122',
      title: '이미슬픈사랑',
      singer: '야다',
    },
    {
      ranking: '35',
      num: '46490',
      title: '너였다면(또오해영OST)',
      singer: '정승환',
    },
    {
      ranking: '36',
      num: '6093',
      title: '낭만고양이',
      singer: '체리필터',
    },
    {
      ranking: '37',
      num: '11019',
      title: '체념',
      singer: '빅마마',
    },
    {
      ranking: '38',
      num: '14684',
      title: '가시',
      singer: '버즈',
    },
    {
      ranking: '39',
      num: '91725',
      title: '한페이지가될수있게',
      singer: '데이식스',
    },
    {
      ranking: '40',
      num: '8797',
      title: 'Tears',
      singer: '소찬휘',
    },
    {
      ranking: '41',
      num: '54825',
      title: '너의번호를누르고',
      singer: '#안녕(Prod.영화처럼)',
    },
    {
      ranking: '42',
      num: '37545',
      title: '스물다섯,스물하나',
      singer: '자우림',
    },
    {
      ranking: '43',
      num: '48585',
      title: '예뻤어',
      singer: '데이식스',
    },
    {
      ranking: '44',
      num: '81061',
      title: '호랑수월가',
      singer: '탑현',
    },
    {
      ranking: '45',
      num: '36707',
      title: '봄봄봄',
      singer: '로이킴',
    },
    {
      ranking: '46',
      num: '34687',
      title: '안아줘',
      singer: '정준일',
    },
    {
      ranking: '47',
      num: '35198',
      title: '나를사랑했던사람아',
      singer: '허각',
    },
    {
      ranking: '48',
      num: '83063',
      title: '파이팅해야지',
      singer: '부석순(세븐틴)(Feat.이영지)',
    },
    {
      ranking: '49',
      num: '76385',
      title: '추억은만남보다이별에남아',
      singer: '정동하',
    },
    {
      ranking: '50',
      num: '97511',
      title: '모든날, 모든순간(Every Day, Every Moment)(키스먼저할까요? OST)',
      singer: '폴킴',
    },
    {
      ranking: '51',
      num: '35774',
      title: 'All For You(응답하라1997 OST)',
      singer: '서인국,정은지',
    },
    {
      ranking: '52',
      num: '39361',
      title: '스토커',
      singer: '10cm',
    },
    {
      ranking: '53',
      num: '18470',
      title: '다시만난세계',
      singer: '소녀시대',
    },
    {
      ranking: '54',
      num: '9281',
      title: 'Endless',
      singer: '플라워',
    },
    {
      ranking: '55',
      num: '97404',
      title: '지나오다',
      singer: '닐로',
    },
    {
      ranking: '56',
      num: '89245',
      title: '아로하(슬기로운의사생활OST)',
      singer: '조정석',
    },
    {
      ranking: '57',
      num: '34683',
      title: '흰수염고래',
      singer: '윤도현밴드',
    },
    {
      ranking: '58',
      num: '19440',
      title: '바보에게…바보가',
      singer: '박명수',
    },
    {
      ranking: '59',
      num: '46716',
      title: '이소설의끝을다시써보려해',
      singer: '한동근',
    },
    {
      ranking: '60',
      num: '82838',
      title: 'Say I Love You',
      singer: '우디',
    },
    {
      ranking: '61',
      num: '14832',
      title: '사랑했나봐',
      singer: '윤도현',
    },
    {
      ranking: '62',
      num: '3800',
      title: '발걸음',
      singer: '에메랄드캐슬',
    },
    {
      ranking: '63',
      num: '35184',
      title: '벚꽃엔딩',
      singer: '버스커버스커',
    },
    {
      ranking: '64',
      num: '82793',
      title: 'Candy',
      singer: 'NCT DREAM',
    },
    {
      ranking: '65',
      num: '10052',
      title: '심',
      singer: '얀',
    },
    {
      ranking: '66',
      num: '10594',
      title: 'One Love',
      singer: 'MC THE MAX',
    },
    {
      ranking: '67',
      num: '16677',
      title: '기다리다',
      singer: '윤하',
    },
    {
      ranking: '68',
      num: '14828',
      title: '나에게로떠나는여행',
      singer: '버즈',
    },
    {
      ranking: '69',
      num: '81242',
      title: '사랑인가봐(사내맞선OST)',
      singer: '멜로망스',
    },
    {
      ranking: '70',
      num: '31943',
      title: '형(兄)',
      singer: '노라조',
    },
    {
      ranking: '71',
      num: '82467',
      title: 'ANTIFRAGILE',
      singer: 'LE SSERAFIM(르세라핌)',
    },
    {
      ranking: '72',
      num: '38263',
      title: '야생화',
      singer: '박효신',
    },
    {
      ranking: '73',
      num: '82885',
      title: 'OMG',
      singer: 'NewJeans',
    },
    {
      ranking: '74',
      num: '81898',
      title: '그라데이션',
      singer: '10cm',
    },
    {
      ranking: '75',
      num: '18446',
      title: '우리의꿈(원피스 OP)',
      singer: '코요태',
    },
    {
      ranking: '76',
      num: '12291',
      title: 'Monologue',
      singer: '버즈',
    },
    {
      ranking: '77',
      num: '31729',
      title: '죽일놈(Guilty)',
      singer: '다이나믹듀오',
    },
    {
      ranking: '78',
      num: '13584',
      title: '나였으면(황태자의첫사랑OST)',
      singer: '나윤권',
    },
    {
      ranking: '79',
      num: '82075',
      title: '새벽에걸려온너의전화는',
      singer: '한동근',
    },
    {
      ranking: '80',
      num: '14238',
      title: '눈의꽃(미안하다사랑한다OST)',
      singer: '박효신',
    },
    {
      ranking: '81',
      num: '53705',
      title: '노래방에서',
      singer: '장범준',
    },
    {
      ranking: '82',
      num: '83361',
      title: 'Kitsch',
      singer: 'IVE(아이브)',
    },
    {
      ranking: '83',
      num: '80788',
      title: '오르트구름',
      singer: '윤하',
    },
    {
      ranking: '84',
      num: '4074',
      title: '금지된사랑',
      singer: '김경호',
    },
    {
      ranking: '85',
      num: '82475',
      title: '떠나보낼준비해둘걸그랬어',
      singer: '임한별',
    },
    {
      ranking: '86',
      num: '31981',
      title: '술한잔해요',
      singer: '지아',
    },
    {
      ranking: '87',
      num: '96806',
      title: 'My Way(돈꽃OST)',
      singer: '이수',
    },
    {
      ranking: '88',
      num: '49522',
      title: '홍연',
      singer: '안예은',
    },
    {
      ranking: '89',
      num: '30868',
      title: '8282',
      singer: '다비치',
    },
    {
      ranking: '90',
      num: '98866',
      title: '그대가내안에박혔다',
      singer: '황치열',
    },
    {
      ranking: '91',
      num: '98727',
      title: '너를만나',
      singer: '폴킴',
    },
    {
      ranking: '92',
      num: '35884',
      title: '바람기억',
      singer: '나얼',
    },
    {
      ranking: '93',
      num: '53651',
      title: '주저하는연인들을위해',
      singer: '잔나비',
    },
    {
      ranking: '94',
      num: '83108',
      title: 'Teddy Bear',
      singer: 'STAYC(스테이씨)',
    },
    {
      ranking: '95',
      num: '16223',
      title: '비행기',
      singer: '거북이',
    },
    {
      ranking: '96',
      num: '96391',
      title: '폰서트',
      singer: '10cm',
    },
    {
      ranking: '97',
      num: '11932',
      title: '오리날다',
      singer: '체리필터',
    },
    {
      ranking: '98',
      num: '97017',
      title: '그날처럼',
      singer: '장덕철',
    },
    {
      ranking: '99',
      num: '81601',
      title: '오르막길',
      singer: '윤종신',
    },
    {
      ranking: '100',
      num: '98245',
      title: '축가',
      singer: '전우성(노을)',
    },
  ],
};

export const playlistDummy = {
  data: [
    {
      playListId: 1,
      title: '퇴사 말릴 때',
      color: 1,
      emoji: '✨',
    },
    {
      playListId: 2,
      title: '눈물이 주룩주룩',
      color: 6,
      emoji: '😥',
    },
  ],
};

export const detailDummy = {
  data: [
    {
      userMusicId: '1', //유저 기준의 노래 아이디들 (한 유저를 기준으로 중복되지 않는 아이디를 가진다)
      playListId: '1',
      musicId: '1',
      num: '44444',
      title: '1111',
      singer: '가수',
      lyricist: '작사',
      composer: '작곡',
      youtubeUrl: 'YoutubeURL',
      nation: '국가',
      orderNum: 1,
    },
    {
      userMusicId: '2',
      playListId: '2',
      musicId: '2',
      num: '44444',
      title: '2222',
      singer: '가수',
      lyricist: '작사',
      composer: '작곡',
      youtubeUrl: 'YoutubeURL',
      nation: '국가',
      orderNum: 2,
    },
    {
      userMusicId: '3',
      playListId: '3',
      musicId: '3',
      num: '44444',
      title: '3333',
      singer: '가수',
      lyricist: '작사',
      composer: '작곡',
      youtubeUrl: 'YoutubeURL',
      nation: '국가',
      orderNum: 3,
    },
  ],
  pageInfo: {
    page: 0,
    size: 2,
    totalElements: 2,
    totalPages: 1,
  },
};
